name: Boxcaster
favicon: null
layout_spectrum: 0.73958
typography_spectrum: 0.4146133742760867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0078ff'
    - '#db2426'
    - '#6b6b6b'
  brandStrength: 0.3454547000583261
  lightness: 0.40879842382855713
  saturation: 0.06615655729547143
  rhythmicContrast: 0.8153904296923429
purpose: []
